version: "3.3"
services:
    nodejs-identity-generator:
        build: ./src/identity
    nodejs-libp2p-signaller:
        depends_on: [identity-generator]
        build: ./srv/p2p
        ports:      
            - "0.0.0.0:9998:9998/udp"
            - "0.0.0.0:9998:9998/tcp"
        command: node signaller.js
        network_mode: "host"
    nodejs-libp2p-client:
        depends_on: [nodejs-libp2p-signaller]
        build: ./srv/p2p
        ports:      
            - "0.0.0.0:9999:9999/tcp"
            - "0.0.0.0:9999:9999/udp"
        command: node client.js
        network_mode: "host"
    nodejs-http-server:
        depends_on: [nodejs-libp2p-client]
        build: ./srv/www
        ports:      
            - "0.0.0.0:80:80/tcp"
        expose:
            - 80
        network_mode: "host"