version: "3.3"
services:
    signaller:
        build: .
        ports:      
            - 9999
            - 9998
        expose:
            - 9999
            - 9998
        volumes:
            - local:/usr/src/app/
        command: node signaller.js
    plient:
        depends_on: [signaller]
        build: .
        ports:      
            - 9999
            - 9998
        expose:
            - 9999
            - 9998       
        volumes:
            - local:/usr/src/app/
        command: node client.js
volumes:
     local: 