version: '3'
services:

  js-libp2p-webrtc-star:
    image: libp2p/js-libp2p-webrtc-star
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - VIRTUAL_PORT=9090
    networks:
      service_network:

  nodejs-libp2p-client:
    depends_on: [js-libp2p-webrtc-star]
    build: ./srv/p2p
    ports:      
        - "0.0.0.0:9998:9998/tcp"
        - "0.0.0.0:9998:9998/udp"
    command: node client.js
    networks:
      service_network:
              
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 9999:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    depends_on:
      - js-libp2p-webrtc-star

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
