version: "3.3"
services:
    star-signal:
        image:      node:alpine
        ports:      [9999]
        build:      github.com/libp2p/js-libp2p-webrtc-star
        command:    "npm run star-signal --port=9999 --host=127.0.0.1 > peers"
    p2p-prolog:
        depends_on: [star-signal]
        build:      .
        volumes:    
            -       ./:/srv