version: "3.3"
services:
    p2p-prolog:
        build:      .    
        image: p2p-prolog:base
        ports:      
            - 9999
            - 9998
        expose:
            - 9999
            - 9998     
        volumes:    
            -       ./:/srv
        command: node ./srv/p2p/signaller.js
    p2p-prolog-signaller:
        depends_on: [p2p-prolog]
        image: p2p-prolog:base
        ports:      
            - 9999
            - 9998
         expose:
            - 9999
            - 9998     
        volumes:    
            -       ./:/srv
        command: node ./srv/p2p/client.js