version: "3.3"
services:

    nginx:
        build: ./srv/www
        environment:
            - VIRTUAL_HOST=${DOMAIN}
            - LETSENCRYPT_HOST=${DOMAIN}
        networks:
            service_network:

    nodejs-libp2p-client:
        build:
          context: ./srv/p2p
        ports:
            - 9999:9999
        network_mode: "host"

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 443:443
            - 80:80
        container_name: nginx-proxy
        networks:
            service_network:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
        depends_on:
            -  nginx

    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        environment:
            NGINX_PROXY_CONTAINER: "nginx-proxy"
        networks:
            service_network:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html


networks:
    service_network:

volumes:
    nginx-certs:
    nginx-vhost:
    nginx-html:
