version: "3.3"
services:
    signaller:
        build: .
        ports:      
            - "0.0.0.0:9998:9998/udp"
            - "0.0.0.0:9998:9998/tcp"
        command: node signaller.js
    client:
        depends_on: [signaller]
        build: .
        ports:      
            - "9999:9999/tcp"
            - "9999:9999/udp"
        command: node client.js
