version: "3.3"
services:
    star-signal:
        image:      node:alpine
        ports:      
            - 9090
            - 80
        expose:
            - 9090
            - 80
        build:      github.com/libp2p/js-libp2p-webrtc-star
        entrypoint: ['node', 'src/sig-server/bin.js', '--port=9090', '--host=127.0.0.1', '> peers']
        volumes:    
            -       ./srv:/srv
    p2p-prolog:
        depends_on: [star-signal]
        build:      .
        ports:      
            - 9090
            - 80
        expose:     
            - 9090
            - 80       
        volumes:    
            -       ./srv:/srv